version: '3.7'
services:
  db:
    image: postgres:14
    container_name: desconto_inss_db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      TZ: America/Fortaleza
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TERM: xterm-256color
    restart: always
    ports:
     - '5432:5432'
    expose:
     - '5432'
  
  web:
    container_name: desconto_inss_web
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && rake db:seeds && rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      TZ: America/Fortaleza
      TERM: xterm-256color
    env_file:
     - ./.env.development
    volumes:
     - .:/home/app/web
     - rubygems:/usr/local/bundle
    ports:
     - '3000:3000'

volumes:
  database:
  rubygems:

